import 'dotenv/config';
import Logger from './utils/Logger.js';
import config from './config.js';
import BotClient from './structures/BotClient.js';
const logger = new Logger('main');
logger.log('Starting up...');
process.on('uncaughtException', (e) => logger.error(e.stack));
process.on('unhandledRejection', (e) => logger.error(e.stack));
const client = new BotClient(config.bot.options);
client.start(config.bot.token);
